### ISSUE TITLE
data browser: when deleting an item, the data browser is not refreshed, so the deleted item stays there

### ISSUE THREAD

**Issue by sorenbs** [graphcool/dashboard#102]

**Comment by brene** [comment]
This seems to be fixed now. Can anybody recreate this?

**Comment by schickling** [comment]
I had a similar problem. Try to create many nodes (> 50) and delete all of them to recreate.

**Comment by brene** [comment]
I have conducted some research on this. And this seems to be a concurrency problem. First the deletion mutation is executed, then the "all" query is executed.

**Comment by marktani** [comment]
Wasn't this problem also related to query-caching on the backend?

**Comment by brene** [comment]
In the front-end it's awaiting all deletion promises. I believe this has to be solved in the backend.

**Comment by sorenbs** [comment]
@marktani We have enabled the query caching layer

**Comment by sorenbs** [comment]
I agree. Looks like a backend issue

**Comment by sorenbs** [comment]
scratch that - it's in the frontend

**Comment by brene** [comment]
LOL  😂 
![image](https://cloud.githubusercontent.com/assets/4989523/17527516/f3f01630-5e6b-11e6-89b4-197912b7554b.png)
vs.
![image](https://cloud.githubusercontent.com/assets/4989523/17527544/1065f924-5e6c-11e6-9338-ba6120ae1715.png)
Fixed that :D

**Comment by schickling** [comment]
Yup, implicit return values are sometimes a bit tricky in JS 😆
