### ISSUE TITLE
Warning in BrowserView, takes long time to load

### ISSUE THREAD

**Issue by marktani** [graphcool/dashboard#105]
For some models, it takes a long time to load the existing nodes.
I get the following warning twice:
`Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the BrowserView component.`

Once for this line: `this.setState({ reachedEnd } as State)` and once for this: `this.setState({ items, loading: false } as State)` in `_loadData` and `_reloadData`.

**Comment by brene** [comment]
Recreate: Click on one model repeatedly multiple times a second.

**Comment by brene** [comment]
Moved to M4 due to BrowserView refactoring
