### ISSUE TITLE
Infinite Loop after renaming a project and clicking on 'Structure'

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#111]
![image](https://i.gyazo.com/ec828a84db9d37f07ff341bd8e7567c0.gif)
It actually doesn't depend on what you click. The reason is that the url doesn't get updated to the new name.

**Comment by schickling** [comment]
Most likely a backend problem. Can you check the network tab for errors?

**Comment by brene** [comment]
Yeah I checked but I guess it's because the front-end doesn't reload with a fresh url with the changed name.

**Comment by brene** [comment]
In the backend, the name is updated and all. @sorenbs and I just checked it, so that should be fine.

**Comment by schickling** [comment]
That's a good point. I think we need a Relay `forceFetch()` here.

**Comment by brene** [comment]
I'll look into it. I believe not a lot of people use the renaming feature. So I'll focus on tests first.
