### ISSUE TITLE
Message when creating molde with invalid name is wrong

### ISSUE THREAD

**Issue by sorenbs** [graphcool/dashboard#129]
![image](https://cloud.githubusercontent.com/assets/281337/17708517/b540a880-63e5-11e6-91df-446f01789641.png)

**Comment by brene** [comment]
Isn't SbsTest valid?

**Comment by sorenbs** [comment]
it is. sbsTest wasn't :-)

But what I wanted to point out is that triggerValid is confusing


also - hope all is well in Karlsruhe!

**Comment by brene** [comment]
Yeah, all is awesome ;-)  and I just fixed this.
