### ISSUE TITLE
Adding nodes to a relation in RelationPopup throws GraphQL error

### ISSUE THREAD

**Issue by marktani** [graphcool/dashboard#131]
![participants](https://cloud.githubusercontent.com/assets/1780597/17731127/38da5f84-646c-11e6-8504-a0bfd1069fdb.png)

I got a Relation participants Todo <-> User, if I click on only one of the users, the following mutation is sent to the server

```
"mutation _ {
      addToParticipants(
        participantsTodoId: "cirp62voc04ce0155zbg1ah2g"
        participantsTodoId: "cirp5dl3h03s801551je1t585"
      ) {
        id
      }
    }
"
```

one of the `participantsTodoId` should be called `todoTodoId`.

**Comment by brene** [comment]
Can't be recreated and should be fixed by now. (reviewed with @marktani )
