### ISSUE TITLE
Relation Editor Popup should have vertical scrollbars

### ISSUE THREAD

**Issue by marktani** [graphcool/dashboard#135]
![filter-popup](https://cloud.githubusercontent.com/assets/1780597/17809395/88bf87d0-6616-11e6-89ed-29b2936487a8.png)

**Comment by brene** [comment]
@schickling can you help me out on this? I'm not certain of the exact implementation of the ScrollBox component. I've looked into it and it seems to be a lot of case-specific code. Let's review it together sometime.

**Comment by schickling** [comment]
I would suggest just to get rid of the `ScrollBox` wrapper in this specific case as it doesn't "destroy" the UI.
