### ISSUE TITLE
Duplicate Permissions

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#137]
Does it make sense to have "Guest" permissions set twice? Or Authenticated with the same user set twice?
![image](https://cloud.githubusercontent.com/assets/4989523/17830342/2b06681c-66c9-11e6-9158-b44e7a41b433.png)

**Comment by brene** [comment]
@schickling can you take a look at this?

**Comment by schickling** [comment]
I think there might be scenarios where a user would actually want to have redundant permissions for let's say "documentation" reasons based on the description. Since it doesn't have any negative affect in terms of our system, I think it's alright to allow this.
