### ISSUE TITLE
Select field content not visible

### ISSUE THREAD

**Issue by sokra** [graphcool/dashboard#14]
![image](https://cloud.githubusercontent.com/assets/1365881/15150742/c203e596-16ce-11e6-8b32-b912fbcdded3.png)

Hint: padding

**Comment by schickling** [comment]
Thanks for reporting @sokra! Could you quickly also tell your used browser + OS?

**Comment by sokra** [comment]
Chrome Windows

**Comment by schickling** [comment]
Okay, thanks! We'll look into it! 👍

**Comment by marktani** [comment]
Do you still have this issue? It should be fixed now.

**Comment by sokra** [comment]
fine now
