### ISSUE TITLE
Cannot read "step" of undefined

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#147]
Probably because of some "assumed" arrival in time of an asynchronous call bug.

**Comment by marktani** [comment]
this sounds like it is related to the Getting Started status...

**Comment by sorenbs** [comment]
This just happened to me when I refreshed the Relations list after adding a Relation. I then refreshed the page ~20 times and it happened again.

**Comment by brene** [comment]
Can somebody still recreate this?

**Comment by brene** [comment]
It seems to be an issue with our combination of redux and relay. I have fixed that by setting the initial state of the getting started to the result of the relay query.
