### ISSUE TITLE
Input validation errors do not reflect current input state

### ISSUE THREAD

**Issue by gajus** [graphcool/dashboard#161]
![pasted image at 2016_08_31 06_59 pm](https://cloud.githubusercontent.com/assets/973543/18140450/7c42bef0-6fad-11e6-954f-d028828f9817.png)

As seen in this screenshot, the error informing me about the relation name capitalisation does not disappear after I have corrected the error.

**Comment by gajus** [comment]
@brene When an issue is closed without a message or commit reference, it is unclear whether an issue was solved or not (or it was not possible to replicate it).

It is a good habit to close issues with commit messages.

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by brene** [comment]
@gajus that is very true! I'm sorry 😞. This is fixed in the "data-browser-update" branch and will be included in the next release. f26bfcd881be3 
Thanks for reporting bugs! Just keep'em coming and I'll try to fix'em 😉
