### ISSUE TITLE
Add scalar JSON type

### ISSUE THREAD

**Issue by schickling** [graphcool/dashboard#189]

**Comment by schickling** [comment]
@matthewmueller

**Comment by brene** [comment]
This has been removed in the backend even because creating relations is the way to handle this. If you really need JSON types then you could also stringify the JSOn and input it as a string

**Comment by schickling** [comment]
There are cases where you'd actually want to store `JSON` values. Unstructured meta information is such a scenario therefore we added support for `JSON` values in the backend, we just don't support them yet in the dashboard.

**Comment by brene** [comment]
Ok, I'll check back with @sorenbs. Last time I heard something different. Is there any reason not to use stringified JSON other than convenience?

**Comment by schickling** [comment]
Convenience is the big deal here since you'd need always to call `JSON.stringify` and `JSON.parse` ruining a good developer experience.

**Comment by brene** [comment]
True and agree.

**Comment by brene** [comment]
I have implemented this is the dev branch (and the type selector needs to uncomment one line to be able to add JSON fields)
There are still some issues in the backend with JSON that I'll start looking into

**Comment by brene** [comment]
It works!

**Comment by brene** [comment]
(in dev)
