### ISSUE TITLE
Editing a user from the Data Browser UI and functionality Issue

### ISSUE THREAD

**Issue by aarmand** [graphcool/dashboard#201]
When you click the edit icon in a data element from the Data Browser, it opens it offscreen to the right. Additionally, the element you have clicked is not identified so write now I am counting the cells in the headings then counting the cells in the edit fields.  Also, clicking any edit icon opens up more than the field you are targeting for editing. If you want to use the edit icon on each field than maybe it should open the field that you clicked it on. Hope this helps.

**Comment by brene** [comment]
I have fixed this in the dev branch and will be included in the next release.
