### ISSUE TITLE
3. Learning the GraphQL Workflow/Adding Queries To Schema

### ISSUE THREAD

**Issue by aarmand** [graphcool/dashboard#213]
How are we copy and pasting this into our code exactly? Is there a way to download the project after we have added Models and fields? 

Also, when I right a new query that I want to use in the playground, it would make sense to have an option to "add query to schema". With your current set up, per the Guide instructions, I copy/paste'd the new query i wanted to use into VSCODE. I had to look for the schema const's because there was no schema file. There might be some reason why you shouldnt do this that I am missing. But the following workflow would be useful. Write a new query, select add to schema if you want to use it, its added to our graphql schema, staging/prod(whatever), version of app schema is updated. Then have a button somewhere to do an update to your local dev code. Or the person can go do a sync via git. 

![graphcool3](https://cloud.githubusercontent.com/assets/2370391/18785342/f9b0316e-8197-11e6-87d2-1e171711f8d3.PNG)

**Comment by schickling** [comment]
Moved to the docs issues: https://github.com/graphcool/docs/issues/19
