### ISSUE TITLE
1.3 Adding an example user

### ISSUE THREAD

**Issue by aarmand** [graphcool/dashboard#214]
Not sure what is going on here. You probably arent done yet. Here is the feedback anyway. On https://docs.graph.cool/guides/implementing-business-logic-using-actions you instruct the user to create a new node and add there email. Images below is what it looks like. You cant really tell what you are supposed to do other than click the green ADD NODE button. After that, the steps are kinda not descriptive. If you click through it you get to notice there is another line on the table. The cells are not labeled and there is no cell for the users name. 
## Step 1
![graphcool4-addnode](https://cloud.githubusercontent.com/assets/2370391/18785818/d0aafc10-819a-11e6-9803-8884a65fe2d8.PNG)
## Step 2
![graphcool4-addnode2 5](https://cloud.githubusercontent.com/assets/2370391/18785819/d0b04fda-819a-11e6-9e0b-15c29f6225ed.PNG)
## Step 3
![graphcool4-addnode2](https://cloud.githubusercontent.com/assets/2370391/18785821/d0b36f58-819a-11e6-9aa3-d704012252ed.PNG)
## Step 4
![graphcool4-addnode3](https://cloud.githubusercontent.com/assets/2370391/18785822/d0b684a4-819a-11e6-950b-ab375f546986.PNG)
## Step 5
![graphcool4-addnode4](https://cloud.githubusercontent.com/assets/2370391/18785817/d0a73288-819a-11e6-85e8-1b8b9fbb3aa4.PNG)

**Comment by marktani** [comment]
moved [to the documentation issues](https://github.com/graphcool/docs/issues/20)
