### ISSUE TITLE
Relay: Actions schema needs to be invalidated when used models change

### ISSUE THREAD

**Issue by schickling** [graphcool/dashboard#219]
`project(){actions(){}}` returns the schema for a given action for a given model. Relay caches this schema.

When a field on the model is renamed or a relation field from the model is renamed, we should invalidate this cache.

Reproduce:

1) Create an action for a model
2) Change a field name for the model
3) Change the action to use the renamed field - It's not there
4) Reload the dashboard
5) Change the action to use the renamed field - it is there

**Comment by brene** [comment]
This is fixed in dev, and will be included in the next release
