### ISSUE TITLE
Relation mutations don't show up under actions dropdown

### ISSUE THREAD

**Issue by thomaslove** [graphcool/dashboard#232]
I can't see my relation mutations under the dropdown on the actions page when the UI suggests I should

**Comment by sorenbs** [comment]
Two questions:

1) this is silly, but have you tried scrolling down?

2) What browser/os are you using?

**Comment by thomaslove** [comment]
1) Doesn't seem to make a difference. Nowhere to scroll

![screen shot 2016-10-01 at 14 23 36](https://cloud.githubusercontent.com/assets/1911414/19014337/af259dea-87e2-11e6-923a-832be1d7d5fa.png)

2) Chrome Version 53.0.2785.116 (64-bit) on OSX 10.11.6

**Comment by marktani** [comment]
I can confirm this obsevation on Linux/Chrome.

**Comment by schickling** [comment]
Thanks for reporting this @thomaslove! You're totally right, this isn't currently possible. We're planning to implement this feature over the next month. Please follow the progress here: https://github.com/graphcool/feature-requests/issues/14
