### ISSUE TITLE
Wrong model pluralization

### ISSUE THREAD

**Issue by sedubois** [graphcool/dashboard#233]
I created a model called `Medium`, which provides the GraphQL field `allMediums` whereas I would expect `allMedia`. Also when creating relations and selecting "many" for this model, it automatically pluralizes it to `Mediums` without any way to edit.

I would suggest to add a configuration to each model where the plural form can be specified, and if not present falling back to an auto-pluralization.

**Comment by schickling** [comment]
That's a great solution. We'll take care of this soon! I'm moving this over to the following repo since it's not purely related to the dashboard: https://github.com/graphcool/feature-requests/issues/13
