### ISSUE TITLE
Custom scalar types

### ISSUE THREAD

**Issue by sedubois** [graphcool/dashboard#235]
It is quite frequent to create fields containing URLs; it would be helpful to be able to specify their type as URL to ensure they are URLs according to some well-known convention.

**Comment by sedubois** [comment]
E.g https://github.com/stylesuxx/graphql-custom-types

**Comment by schickling** [comment]
Would constraints as described here solve the problem for you? https://github.com/graphcool/feature-requests/issues/10

**Comment by sedubois** [comment]
@schickling yes!
