### ISSUE TITLE
Add unique constraint on a field without permissions

### ISSUE THREAD

**Issue by marktani** [graphcool/dashboard#236]
> Got "internal server error" when trying to add a unique constraint on a field which doesn't have any permissions configured.

![untitled](https://cloud.githubusercontent.com/assets/1780597/19016815/4c756278-8825-11e6-98eb-88eaab999e3a.png)

thanks to @sedubois

**Comment by schickling** [comment]
This is a backend problem and will be fixed shortly. I'm closing this for now as @sorenbs is taking care of it.

**Comment by sorenbs** [comment]
This was most likely caused by there being duplicates in the column before adding the unique index. @marktani - are you sure this was related to there being no permission?

**Comment by marktani** [comment]
@sedubois might know :)

**Comment by sorenbs** [comment]
Ahh, didn't see that. Thanks!
