### ISSUE TITLE
Daily session timeout

### ISSUE THREAD

**Issue by sedubois** [graphcool/dashboard#250]
The Graph.cool session times out every day, forcing a new login, even when keeping a graph.cool browser tab open several days in a row. Combined with the fact that my Chrome browser does not autofill the login/password fields (which I guess also leads to https://github.com/graphcool/dashboard/issues/227), it gets quite repetitive to manually enter these login/password.

**Comment by schickling** [comment]
I totally agree. This has been on our todo list for quite a while now. I'll make sure that we'll get this done asap!

**Comment by schickling** [comment]
This should be fixed now. Sessions now last 30 days. Please let us know if this is still an issue!

**Comment by sedubois** [comment]
Thanks, appreciated 😊
