### ISSUE TITLE
ID should always be the first column in databrowser

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#272]
![image](https://cloud.githubusercontent.com/assets/4989523/19309189/b450dc72-9083-11e6-9874-ee2ceade44b6.png)

I find it weird that the ID field is to the right of the "roles" field and there is no way to change it back.

**Comment by timsuchanek** [comment]
@brene Does this still happen in the latest dashboard?

**Comment by brene** [comment]
Looks like it's fixed.
