### ISSUE TITLE
It's confusing that the id field is moving around in the field list

### ISSUE THREAD

**Issue by sorenbs** [graphcool/dashboard#28]
I understand that the fields are sorted alphabetically, but maybe there should be an exception for the id field?

**Comment by schickling** [comment]
Could you describe what you mean by "moving around"?

**Comment by sorenbs** [comment]
It's not actually jumping around :-) 

I would expect it to always be at the top as it is a special field the user did not add themself and might not really care about. But as all fields are simply sorted alphabetically the id field can be one or more positions down the list depending on what other fields they add.

**Comment by marktani** [comment]
It is behaving like you want on the dev branch - maybe you are talking about production stage here?

**Comment by marktani** [comment]
Sorry, I thought you mean the columns in the Browser View. You are actually talking about the Structure View! I will deal with that :)
