### ISSUE TITLE
Can't add user with auth0

### ISSUE THREAD

**Issue by sedubois** [graphcool/dashboard#281]
I configured my User model with Auth0. When creating user through dashboard, I add the firstName, lastName etc, but for `auth0UserId` I don't put anything as the cell shows "auth0UserId will be gener..." (would be good to show full text BTW). When I submit I get:

![untitled2](https://cloud.githubusercontent.com/assets/4217871/19435849/9de3a384-9475-11e6-9159-20765da35249.png)

And a weird row with grey rectangles gets added at the bottom of the table: 

<img width="1244" alt="screen shot 2016-10-17 at 14 28 37" src="https://cloud.githubusercontent.com/assets/4217871/19435928/0d04d5e4-9476-11e6-8591-13095844ccdb.png">

If I refresh the page, that row is gone.

**Comment by sedubois** [comment]
Also see https://github.com/graphcool/dashboard/issues/282 when trying to use Playground.

**Comment by sorenbs** [comment]
Hi Sebastien

It is currently not possible to add users through the databrowser. We will update the interface to reflect this.

I'm looking into why it doesn't work for you through GraphiQL. It should.
