### ISSUE TITLE
Can't add user with auth0 through playground

### ISSUE THREAD

**Issue by sedubois** [graphcool/dashboard#282]
I have a User model with Auth0, tried to create a new User through a Relay query:

```
mutation {
  createUser(input: {
    firstName: "foo"
    lastName: "bar"
    avatarUrl: "http://dreamatico.com/data_images/kitten/kitten-1.jpg"
    slug: "foobar"
    clientMutationId: "myClientMutationId"
    authProvider: {
      auth0: {
        idToken: "myAuth0IdToken"
      }
    }
  }) {
    user {
      id
    }
  }
}
```

But got:
```
{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createUser"
      ],
      "code": 3023,
      "message": "User already exist with that information",
      "requestId": "ciudzd39m125r0124j2ny4sbb"
    }
  ]
}
```

However, I don't have such data in my DB.

Also, GraphQL requires a `clientMutationId` but I have no idea what that is.

**Comment by sorenbs** [comment]
First, clientMutationId is a field used by Relay to associate queries and responses. The server will always return the same clientMutationId as ser client specified. If you are using Relay this will be added automatically, and if you are using the playground you can specify any value.

Now to your issue :-) I suspect that you might not be specifying a valid Auth0 idToken. It has to be a jwt issued by Auth0. To verify you can try to decode it at jwt.io

It should contain a `sub` field and look like this:

```
{
  "iss": "https://sorenbs.eu.auth0.com/",
  "sub": "auth0|57d2e5e6f78ad35973d0f7a6",
  "aud": "VawPZqBYrkmVnE6FpCfHXgOOd5vGY0Xg",
  "exp": 1473475654,
  "iat": 1473439654
}
```

I'll update our error messages to be more helpful.

**Comment by sedubois** [comment]
Thanks, indeed. In this case the auth0 idToken type should reflect this, currently it is simply `String!`.

**Comment by sorenbs** [comment]
That's an interesting thought. What would you have expected the type of idToken to be?

There is no way a type can encapsulate all the requirements of a auth0 idToken, so to me it seems reasonable that it should be a string! with proper runtime validation (and a proper error message). Curious to hear if you have a better suggestion.

**Comment by sedubois** [comment]
Well, at least being reminded that this should be a JWT without needing to run into the error to figure it out. So making this info available in GraphiQL description at minimum, and otherwise just creating a custom type which is a clone of String but named JWT? And you could progressively add static checks in it depending on GraphQL's abilities? (I'm not familiar with those details)

**Comment by sorenbs** [comment]
I think that is a very reasonable approach. Thanks for bringing this up!

**Comment by sorenbs** [comment]
GraphiQL now includes a proper description for the idToken field and the error will point you to the auth0 docs if the idToken is invalid.

Thanks again for reporting this!

**Comment by ernoaapa** [comment]
If you end up here (like I did) because when you create user and you get error `The provided idToken is invalid`, that's because you probably need to change the algorithm in Auth0 settings to HS256.

https://github.com/graphcool/feature-requests/issues/145#issuecomment-318968578
