### ISSUE TITLE
Authentication flow forces two queries, relies on try-catch and undocumented API

### ISSUE THREAD

**Issue by sedubois** [graphcool/dashboard#294]
The [auth0-lock-example](https://github.com/graphcool-examples/auth0-lock-example/blob/master/src/App.js) shows that two queries are needed to authenticate a (potentially new) user:
- issue a `createUser` mutation
- issue a `signinUser` mutation

The `createUser` mutation is in theory sufficient, as it returns the graphcool token with which to perform subsequent queries; but because it can potentially fail (if user already exists), the second query is necessary.

It could be quite useful to have a single `signInOrCreateUser` mutation to simplify this common case?

**Comment by schickling** [comment]
That's a very good point. We considered exactly that use case but there are a couple of problems with it. One of it is that if a `User` model contains a field called `token` then the `createUser` mutation would break because there are two options for `token`.

I totally see your point and this is definitely a tradeoff between a "clean" system design and convenience. Maybe you have some other suggestions we haven't thought about yet?

**Comment by sedubois** [comment]
> if a User model contains a field called token then the createUser mutation would break because there are two options for token

That sounds like a design issue that would be solved while configuring the backend, not a production problem? In such a case I see no problem in having the mutation yield an error, and let the developer fix the schema properly (rename the pre-existing `token` to something else). Or maybe I misunderstood your explanation.

The more general remark is that the backend should not force the try-catching of an error for what is really a nominal flow which would occur all the time.

**Comment by schickling** [comment]
I totally see your point here. I'll leave this up for discussion. I'd be happy to change this further down the road since it wouldn't mean a breaking change. I think in general it's a good idea to let the customer (you in this case) configure as many system artifacts as possible (like the `token` response field).

**Comment by sedubois** [comment]
Thanks, I updated the issue title. Several things, IMHO:
- 2 queries whereas 1 should be enough
- try-catch-rethrow (a code smell)
- manual introspection within an error to look at a specific code: `!e.rawError || e.rawError[0].code !== 3023`
- code above relies on various undocumented API elements ("look at the code of raw error number zero and check if it has the magic value `3023`"), not leveraging the GraphQL documented type system
- the code above is actually client-specific, which can take a while to figure out. I use Relay and in my promisified mutation I had to create an `onFailure` handler with `onFailure: (tx) => reject(tx.getError())` and in my catch: `if (!e.source || e.source.errors[0].code !== 3023)`. Relay doesn't apparently document `RelayMutationTransaction` on its website and I had to Google to find this [issue](https://github.com/facebook/relay/issues/696#issuecomment-166485586) to figure it out.

It took quite a while for me to figure it out, and it adds on top of the learning curve to get Auth0 working. If all this was provided in a single specific mutation, the user could just rely on its type system visible through the clean Dashboard, no need to know about magic numbers and searching for unexisting/limited documentation etc.

**Comment by sedubois** [comment]
FYI the error handling signature needed for Apollo:
```js
      if (!e.graphQLErrors || e.graphQLErrors[0].code !== 3023) {
        throw e;
      }
```
Relay signature is in the previous comment and Lokka signature is visible in the example referenced in the OP.
