### ISSUE TITLE
Avoid forcing the use of Relay REQUIRED_CHILDREN?

### ISSUE THREAD

**Issue by sedubois** [graphcool/dashboard#295]
I'm trying to get my head around this, my understanding so far is in this [Relay issue](https://github.com/facebook/relay/issues/1430): AFAIK, I have trouble getting my Relay store to update after authentication because I'm forced to use `REQUIRED_CHILDREN` to indicate which data to return, but that doesn't update the store because it's not yet aware of any component consuming that data. In general using `REQUIRED_CHILDREN` seems quite cumbersome, and the [Learn Relay tutorial](https://learnrelay.org/mutations/mutation-types/) says: "Note that this type is rarely used and is only applicable in very specific use cases." It would be great to be able to avoid it.

If I understand the problem right (hem), a clean alternative could be to make sure a `user` field always exists on `viewer`, even before authentication (with a `null` value or something), so that it already has a dataID and enables subsequently using `FIELDS_CHANGE` to update it: "Any field in the payload that can be correlated by DataID with one or more records in the client-side store will be merged with the record(s) in the store."

I could maybe in that case pass this user ID to the `createUser`/`signinUser` mutations and do:

```
type: 'FIELDS_CHANGE',
fieldIDs: {
  user: this.props.userId,
},
```

**Comment by schickling** [comment]
Are you referring to the usage of `REQUIRED_CHILDREN` in [this file](https://github.com/graphcool/dashboard/blob/master/src/mutations/LoginMutation.ts). For general questions about Relay + Graphcool we'd love to answer your questions [on Stackoverflow](http://stackoverflow.com/questions/tagged/graphcool) to keep this repo focussed on the dashboard of Graphcool.

**Comment by sedubois** [comment]
This was an "issue" about the Graphcool API (don't know where I should file issues about that?) 
And I posted in GitHub because I saw it more as an issue than a question at this point, but that's probably wrong, as you remind with your link above that it's possible to sign in with Relay correctly. I'll open a SO ticket if needed.

**Comment by sedubois** [comment]
The file you pointed to isn't what I meant, as I'm talking of the `signinUser` and `createUser` on your API.
