### ISSUE TITLE
Empty Space at Bottom of Page

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#48]
Because the ScrollBar height is not subtracted to the total page height, there is an empty space below the main area.
![screen shot 2016-06-11 at 3 13 33 pm](https://cloud.githubusercontent.com/assets/4989523/15985235/19e419da-2fe7-11e6-83b7-1d76d8a4b305.png)

**Comment by schickling** [comment]
Is that still the case for you @brene?

**Comment by brene** [comment]
Nope, it's fixed now :-)
