### ISSUE TITLE
Popup when saving my changed name and email is quite annoying

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#57]
![image](https://cloud.githubusercontent.com/assets/4989523/16268934/a1fdb14e-3890-11e6-9182-343747c23cf5.png)
This is kinda annoying. A popup is blocking my user input after saving. A bubble should just appear on the top of the page showing that my changes has been saved.

**Comment by marktani** [comment]
Feedback is now given with a nice notification instead with a in-your-face popup :+1:
