### ISSUE TITLE
Onboarding message is hard to read

### ISSUE THREAD

**Issue by schickling** [graphcool/dashboard#62]
![attachment-2](https://cloud.githubusercontent.com/assets/1567498/16304457/dca9f238-3955-11e6-81a3-8f0063fc9446.png)

Thanks to @picsoung for reporting!

**Comment by brene** [comment]
Any further elaboration on this? Is the font-size too small?

**Comment by schickling** [comment]
I think it's the green-on-green.

**Comment by brene** [comment]
you mean the main issue is the tether colors are too similar?

**Comment by schickling** [comment]
Yes. @julianbauer what do you think?

**Comment by brene** [comment]
![image](https://cloud.githubusercontent.com/assets/4989523/17819933/9f9ab1bc-664a-11e6-999a-d0d3c902e5d5.png)
Is a drop shadow like this good enough for now?

**Comment by brene** [comment]
I think we already iterated somewhat on this problem. See how the text is darker now?

**Comment by schickling** [comment]
I think that definitely helps. Not sure if it's intended that the text is darker. @julianbauer ?
