### ISSUE TITLE
Relay example doesn't work in onboarding process

### ISSUE THREAD

**Issue by schickling** [graphcool/dashboard#63]
![attachment-3](https://cloud.githubusercontent.com/assets/1567498/16304494/fa2e6ae6-3955-11e6-87f6-cf1ad9306a12.png)

> on this final screen few stuff happen:  React+Relay was first selected and I could not click on React+Apollo, the state of the button was not changing, still white.

> I had to click on “step 3” in the left menu bar to activate changes.

> Same thing to check the “checking status” working and show the congrats screen.

Thanks again for @picsoung for reporting this problem!

**Comment by marktani** [comment]
Should be fixed. Needs to be confirmed once the code is live.
