### ISSUE TITLE
Prevent deleting the last remaining project

### ISSUE THREAD

**Issue by marktani** [graphcool/dashboard#68]

**Comment by marktani** [comment]
Redirecting needs to be fixed. Currently we are using `window.location.pathname = '/'`. Before we used `this.context.router.replace(`/${this.props.params.projectName}`)` but that doesn't work either.

**Comment by sorenbs** [comment]
The api will now return an error when you try to delete the last project for a client. @marktani Do you want to keep this issue open to track the change in redirect behaviour or do you have a separate issue for that?

**Comment by marktani** [comment]
See #70.
