### ISSUE TITLE
don't submit empty strings when storing empty text field (causes unique constraint violations)

### ISSUE THREAD

**Issue by sorenbs** [graphcool/dashboard#78]
data browser: when saving a model with empty values in non required text field the empty string is submitted. This is an issue for unique fields, as only one occurrence of "" is allowed, whereas the intended null value is allowed to occur multiple times.

This is currently an issue for the User model as email is unique and optional(due to integrations that don't require an email). So when you create the second user in the dashboard without an email it fails.

Note: this is easy to fix for create item, as we can simply omit the field. For update we have to figure out the intent of the user:

1. Set an existing text value to the empty string. omitting the fields in this case won't work
2. Set an existing text value to null. omitting the field in this case also won't work.

**Comment by schickling** [comment]
See #82
