### ISSUE TITLE
Error in the getting started tour

### ISSUE THREAD

**Issue by mschoepe** [graphcool/dashboard#8]
In the example at the beginning one should create a todo. Before add new todo !

- The string is ok
- The boolean is is invisible in the selection. After creating it has the status to have been chosen.

**Comment by schickling** [comment]
Update: This seems to be a Win 7 specific issue.

![todo-2](https://cloud.githubusercontent.com/assets/1567498/15100281/99ada4fe-156d-11e6-8d7d-2d67464bb170.jpg)
![todo-1](https://cloud.githubusercontent.com/assets/1567498/15100283/9c1632e2-156d-11e6-91fd-f852a6a008e4.jpg)
