### ISSUE TITLE
data-tab: let the user set values to null

### ISSUE THREAD

**Issue by schickling** [graphcool/dashboard#82]
It's currently not clear and sometimes dependent on the type whether you can set a non-required value back to `null`.

**Comment by schickling** [comment]
Related to #78

**Comment by schickling** [comment]
@julianbauer do you have any good idea for this one?

**Comment by julianbauer** [comment]
When editing text-fields, I could easily set values to null by just deleting all the content...If that's not gonna change, I'd show an apropriate icon while in edit mode (e.g. visualization of Delete-Key, Cross, Eraser, or just an italic 'null') in the top right corner.

**Comment by schickling** [comment]
Deleting all the content is sometimes ambiguous for example for strings it could mean a user wants an empty string vs null. Also custom cells for boolean or datetime don't allow for the option to delete the value entirely.

So I guess your suggestion in terms of a delete button is the way to go 👍
