### ISSUE TITLE
Issues with Date/Time picker

### ISSUE THREAD

**Issue by marktani** [graphcool/dashboard#86]
- Copy/pasting a String like `2016-07-08T00:00:00.000Z` in a new Date/Time field and then clicking Ok closes the date time picker but doesn't close the input field. An error `Uncaught TypeError: t.toISOString is not a function` appears in the console. I have to click a date in the date/time to continue, which will overwrite the pasted String.
- If I am clicking on a day like 2016-07-29, the input field will say `2016-07-29 00:00:00+0200`, if I accept this it will be converted to `2016-07-29 22:00:00.000Z`. It probably should have been `2016-07-29 00:00:00+0000` from the start.

**Comment by schickling** [comment]
Yeah, that's some kinda shortcoming of the used datetime picker. We should rather fix it or create our own Datetime picker. The latter one might even be faster.

**Comment by brene** [comment]
96a6cb985be5a02545ec335112d2348ba2ad3f3a
