### ISSUE TITLE
"Add item" sometime doesn't display an input row

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#89]
Sometimes clicking the "Add item" button doesn't show the input row. (only happens in dev branch)
This happens in the "getting started" tutorial with the "Todo" model.
![image](https://cloud.githubusercontent.com/assets/4989523/17408058/ff5c6dda-5a69-11e6-8bdf-95ae26d7923f.png)

**Comment by schickling** [comment]
On it!
