### ISSUE TITLE
Getting started sample lokka project throws errors

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#90]
When running the sample project as stated in the getting started section will result in an unusable todo list app. Adding a new item just clears the input box text. 
Console output:
![image](https://cloud.githubusercontent.com/assets/4989523/17408193/8f30e8be-5a6a-11e6-981d-03b0eb63c150.png)

**Comment by marktani** [comment]
I will update all the examples over the weekend anyway, thanks for this issue.
